import assert from 'node:assert/strict';
import { spawnSync, execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cli = path.join(root, 'src', 'cli.js');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'test-gap-finder-'));
function git(args) { return execFileSync('git', args, { cwd: tmp, encoding: 'utf8' }); }
git(['init', '-b', 'main']);
git(['config', 'user.email', 'test@example.com']);
git(['config', 'user.name', 'Test User']);
fs.mkdirSync(path.join(tmp, 'src'), { recursive: true });
fs.writeFileSync(path.join(tmp, 'package.json'), JSON.stringify({ scripts: { test: 'node --test' } }));
fs.writeFileSync(path.join(tmp, 'src/api.js'), 'export const v = 1;\n');
git(['add', '.']);
git(['commit', '-m', 'initial']);
fs.writeFileSync(path.join(tmp, 'src/api.js'), 'export const v = 2;\n');
const out = execFileSync(process.execPath, [cli], { cwd: tmp, encoding: 'utf8' });
assert.match(out, /request\/response/);
assert.match(out, /npm test/);
const failed = spawnSync(process.execPath, [cli, '--fail-on-gap'], { cwd: tmp, encoding: 'utf8' });
assert.equal(failed.status, 2);
console.log('test-gap-finder tests passed');
